- src/AiLibrary.flix
- src/Core.flix
- src/Display.flix
- src/Engine.flix
- test/TestDisplay.flix
Fixes some of #4. Dependent on #14
> Add Ai Library

- src/AiLibrary.flix
- test/TestDisplay.flix
> add Ai to spin and shoot

- src/AiLibrary.flix
- src/GridGraph.flix
- test/TestDisplay.flix
> feat: add pathfinding

- src/Core.flix
- src/Engine.flix
> implement walking

- .github/workflows/build-nightly.yaml
This ensures we are up to speed with Flix master.
> create a nightly test

- src/AiLibrary.flix
- src/Engine.flix
- src/GridGraph.flix
- test/TestDisplay.flix
fix bug with the last steps of path finding, also expanding the test
> fix: `GridGraph.findShortestPath` last step bug

- src/Core.flix
- src/Engine.flix
- src/Noise.flix
- test/TestDisplay.flix
> Feat: Add random board gen

- src/AiLibrary.flix
- src/Core.flix
- src/Engine.flix
- src/GridGraph.flix
- test/TestDisplay.flix
> use Coordinates type alias

- src/AiLibrary.flix
- src/Core.flix
- src/Display.flix
- src/Engine.flix
- test/TestDisplay.flix
Move the move logic into a map in the game state. Part of #40
what do you think @mlutze
> refactor: Remove `Player`

- src/AiLibrary.flix
- src/Core.flix
Step 1 for the Stateable type class
fixes #57
> refactor: change AiState to shaped enum

- README.md
> docs: minimal README

- src/Core.flix
- test/TestBoard.flix
- test/TestDisplay.flix
> feat: parse board from string

- src/AiLibrary.flix
- src/Core.flix
- src/Engine.flix
- src/GridGraph.flix
- src/Utils/Utils.flix
- test/TestDisplay.flix
> feat: add direction to pathfinding

- src/Engine.flix
> refactor: add runGame function

- src/Options.flix
- test/TestOptions.flix
> feat: add seed command line option

- src/Display.flix
Now covering all the ANSI colors even though they are not that distinct
> feat: add more player colors

- src/AiLibrary.flix
- test/TestDisplay.flix
> feat: smart search and destroy AI

- src/AiLibrary.flix
- src/Core.flix
- src/Engine.flix
- src/GridGraph.flix
- src/State.flix
- src/Utils/Utils.flix
- test/TestDisplay.flix
> refactor: separate gamestate and ai info

- CONVENTIONS.md
- README.md
> docs: add CONVENTIONS.md

- CONVENTIONS.md
- src/AiLibrary.flix
- src/Core.flix
- src/Display.flix
- src/GridGraph.flix
- src/Noise.flix
- src/Options.flix
- src/State.flix
- src/Utils/RegionedRandom.flix
- src/Utils/Utils.flix
> docs: add code blocks to CONVENTIONS.md

- src/Main.flix
- src/Options.flix
- test/TestOptions.flix
> feat: add more cli options

- src/Config.flix
- src/Main.flix
> feat: improve error messages for CLI and config

- README.md
- src/Config.flix
This is just to unbreak things. Afterward we should be able to leverage the new Jsonable type class.
> chore: update flix-json dependency
